import fakeImage from "../images/fakeImage.png";

const fakeMoviesArray = [
    {
        title: "1 слово о дизайне",
        duration: "107",
        image: fakeImage,
        saved: false,
        movieId: "123",
    },
    {
        title: "2 слова о дизайне",
        duration: "33",
        image: fakeImage,
        saved: false,
        movieId: "123234",
    },
    {
        title: "3 слова о дизайне",
        duration: "107",
        image: fakeImage,
        saved: true,
        movieId: "123213",
    },
    {
        title: "4 слова о дизайне",
        duration: "107",
        image: fakeImage,
        saved: false,
        movieId: "12222",
    },
    {
        title: "5 слов о дизайне",
        duration: "57",
        image: fakeImage,
        saved: true,
        movieId: "134444",
    },
    {
        title: "6 слов о дизайне",
        duration: "107",
        image: fakeImage,
        saved: false,
        movieId: "2377",
    },
    {
        title: "7 слов о дизайне",
        duration: "107",
        image: fakeImage,
        saved: false,
        movieId: "12000",
    },
    {
        title: "8 слов о дизайне",
        duration: "107",
        image: fakeImage,
        saved: false,
        movieId: "15653",
    },
    {
        title: "9 слов о дизайне",
        duration: "60",
        image: fakeImage,
        saved: false,
        movieId: "222215653",
    },
    {
        title: "10 слов о дизайне",
        duration: "107",
        image: fakeImage,
        saved: false,
        movieId: "1237667",
    },
    {
        title: "11 слов о дизайне",
        duration: "61",
        image: fakeImage,
        saved: true,
        movieId: "123556",
    },
    {
        title: "12 слов о дизайне",
        duration: "107",
        image: fakeImage,
        saved: false,
        movieId: "23000",
    },
    {
        title: "13 слов о дизайне",
        duration: "107",
        image: fakeImage,
        saved: false,
        movieId: "23678",
    },
    {
        title: "14 слов о дизайне",
        duration: "107",
        image: fakeImage,
        saved: false,
        movieId: "0123",
    },
    {
        title: "15 слов о дизайне",
        duration: "107",
        image: fakeImage,
        saved: false,
        movieId: "0123234",
    },
    {
        title: "16 слов о дизайне",
        duration: "107",
        image: fakeImage,
        saved: true,
        movieId: "0123213",
    },
    {
        title: "17 слов о дизайне",
        duration: "107",
        image: fakeImage,
        saved: false,
        movieId: "012222",
    },
    {
        title: "18 слов о дизайне",
        duration: "107",
        image: fakeImage,
        saved: true,
        movieId: "0134444",
    },
    {
        title: "19 слов о дизайне",
        duration: "107",
        image: fakeImage,
        saved: false,
        movieId: "02377",
    },
    {
        title: "20 слов о дизайне",
        duration: "107",
        image: fakeImage,
        saved: false,
        movieId: "012000",
    },
    {
        title: "21 слов о дизайне",
        duration: "107",
        image: fakeImage,
        saved: false,
        movieId: "015653",
    },
    {
        title: "22 слов о дизайне",
        duration: "107",
        image: fakeImage,
        saved: false,
        movieId: "01237667",
    },
    {
        title: "23 слова о дизайне",
        duration: "107",
        image: fakeImage,
        saved: true,
        movieId: "0123556",
    },
    {
        title: "24 слова о дизайне",
        duration: "107",
        image: fakeImage,
        saved: false,
        movieId: "023000",
    },
    {
        title: "25 слов о дизайне",
        duration: "107",
        image: fakeImage,
        saved: false,
        movieId: "023678",
    },
    {
        title: "26 слов о дизайне",
        duration: "107",
        image: fakeImage,
        saved: false,
        movieId: "023670008",
    },
];

export default fakeMoviesArray;